name: Bug Report
description: Report a bug or issue with the project.
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the bug you encountered.**

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-check
      description: Please confirm that you have searched for duplicate issues before creating this one.
      options:
        - label: I have searched the existing issues and none cover this bug.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
      placeholder: "Detailed description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug.
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "Expected behavior"
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "Actual behavior"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment (e.g., OS, browser, Node version).
      placeholder: "Environment details"

  - type: input
    id: version
    attributes:
      label: Version
      description: Provide the version of the project where you encountered the bug.
      placeholder: "Version number"
    validations:
      required: true
