name: generate-release

on:
  release:
    types: [ published ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  platforms: linux/amd64,linux/arm64

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [ local, external ]

    permissions:
      contents: read
      packages: write

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{version}}-${{ matrix.type }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.type }}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}-${{ matrix.type }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.${{ matrix.type }}
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Version output
        id: version
        run: echo "version=${{ steps.meta.outputs.version }}" >> "$GITHUB_OUTPUT"
